name: Daily WNBA Scraper

on:
  schedule:
    - cron: "0 14 * * *"  #10 AM EST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: |
          TODAY=$(date +%Y-%m-%d)
          END_DATE="2025-09-11"
          
          if [[ "$TODAY" > "$END_DATE" ]]; then
            exit 0
          fi
          
          python scrape_props.py

      - name: Commit and push updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add props.json
          git commit -m "Update scraped data ($TODAY)" || echo "No changes to commit"
          git push
