name: Run WNBA Models and Update Player Box

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  run-models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run master_file.py
        run: python master_file.py

      - name: Run update_playerbox.py
        run: python update_playerbox.py
