name: Models

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  run-models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run master_file.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python master_file.py
