name: PlayerBox

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run scrape script (May–Oct only)
        run: |
          month=$(date -u +"%m")
          if [ $month -ge 5 ] && [ $month -le 10 ]; then
            python scrape_playerbox.py
          else
            echo "Skipped"
          fi
