name: PlayerBox

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Run scrape script (May–Oct only)
        run: |
          month=$(date -u +"%m")
          if [ $month -ge 5 ] && [ $month -le 10 ]; then
            python scrape_playerbox.py
          else
            echo "Skipped"
          fi

      - name: Commit updated CSV
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playerboxes/player_box_2025.csv
          git commit -m "Update player box CSV [skip ci]" || echo "No changes to commit"
          git push
